on:
  push:
    branches: ['main']
    paths:  # Deploy when they are changes on ...
      - '.github/workflows/deploy.yml'  # This file
      - 'docs/**'  # Any file in docs/
      - 'pyproject.toml'  # A new version of aframexr is released (to update notebooks)
  workflow_dispatch:

jobs:
    start-mybinder-build:
      runs-on: ubuntu-latest

      steps:
        - name: Access to the repository's URL in MyBinder
          # Use -L for redirections and "&" for continuing with the next actions
          run: curl -L https://mybinder.org/v2/gh/davidlab20/TFG/${{ github.sha }} &

    build:
        runs-on: ubuntu-latest
        env:
          OUTPUT_DIR: github_pages

        steps:
          # Checkout and install dependencies
          - name: Checkout
            uses: actions/checkout@v4

          - name: Install marimo and jinja2
            run: pip install marimo jinja2

          - name: üìÑ Export notebooks
            working-directory: docs/notebooks
            run: |
              mkdir -p ../${OUTPUT_DIR}/notebooks

              for nb in *_notebook.py; do
                name=$(basename "$nb" .py | tr '_' '-')  # Notebook name (without extension and replacing '_' with '-')
                mode="edit"
                [[ "$nb" == "get_started_notebook.py" ]] && mode="run"
                marimo export html-wasm "$nb" -o ../${OUTPUT_DIR}/notebooks/$name.html --mode $mode
              done

          - name: Build Jinja2 pages
            working-directory: docs
            run: python3 build.py

          - name: üì¶ Upload Pages Artifact
            uses: actions/upload-pages-artifact@v3
            with:
                path: docs/${{ env.OUTPUT_DIR }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            pages: write
            id-token: write

        steps:
            - name: üåê Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                path: docs/${{ env.OUTPUT_DIR }}
                artifact_name: github-pages
