on:
  push:
    branches: ['main']
    paths:  # Deploy when they are changes on ...
      - '.github/workflows/deploy.yml'  # This file
      - 'docs/**'  # Any file in docs/
      - 'pyproject.toml'  # A new version of aframexr is released (to update notebooks)
  workflow_dispatch:

jobs:
    start-mybinder-build:
      runs-on: ubuntu-latest

      steps:
        - name: Access to the repository's URL in MyBinder
          # Use -L for redirections and "&" for continuing with the next actions
          run: curl -L https://mybinder.org/v2/gh/davidlab20/TFG/${{ github.sha }} &

    build:
        runs-on: ubuntu-latest

        steps:
          # Checkout and install dependencies
          - name: Checkout
            uses: actions/checkout@v4

          - name: Install marimo and jinja2
            run: pip install marimo jinja2

          - name: üìÑ Export notebooks
            working-directory: docs/notebooks
            run: |
              marimo export html-wasm --show-code get_started_notebook.py -o get-started-notebook.html --mode run

              marimo export html-wasm simple_chart_notebook.py -o simple-chart-notebook.html --mode edit
              marimo export html-wasm multiple_chart_notebook.py -o multiple-chart-notebook.html --mode edit
              marimo export html-wasm filtered_chart_notebook.py -o filtered-chart-notebook.html --mode edit
              marimo export html-wasm rotated_chart_notebook.py -o rotated-chart-notebook.html --mode edit
              marimo export html-wasm image_and_gltf_notebook.py -o image-and-gltf-notebook.html --mode edit
              marimo export html-wasm aggregated_chart_notebook.py -o aggregated-chart-notebook.html --mode edit
              marimo export html-wasm simple_element_notebook.py -o simple-element-notebook.html --mode edit

          - name: Build Jinja2 pages
            working-directory: docs
            run: python3 build.py --production

          - name: üì¶ Upload Pages Artifact
            uses: actions/upload-pages-artifact@v3
            with:
                path: docs/github_pages

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            pages: write
            id-token: write

        steps:
            - name: üåê Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: github-pages