on:
  push:
    branches: ['main']
    paths:  # Deploy when they are changes on ...
      - '.github/workflows/deploy.yml'  # This file
      - 'docs/**'  # Any file in docs/
      - 'pyproject.toml'  # A new version of aframexr is released (to update notebooks)
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          # Checkout and install dependencies
          - name: Checkout
            uses: actions/checkout@v4

          - name: Install marimo and jupytext
            run: pip install marimo jupytext

          # Marimo notebooks
          - name: üìÑ Export Get Started notebooks
            working-directory: docs/get_started
            run: |
              marimo export html-wasm --show-code get_started_notebook.py -o get-started-notebook.html --mode run

          - name: üìÑ Export Example notebooks
            working-directory: docs/examples/notebooks
            run: |
              marimo export html-wasm simple_chart_notebook.py -o simple-chart-notebook.html --mode edit
              marimo export html-wasm multiple_chart_notebook.py -o multiple-chart-notebook.html --mode edit
              marimo export html-wasm filtered_chart_notebook.py -o filtered-chart-notebook.html --mode edit
              marimo export html-wasm rotated_chart_notebook.py -o rotated-chart-notebook.html --mode edit
              marimo export html-wasm image_and_gltf_notebook.py -o image-and-gltf-notebook.html --mode edit
              marimo export html-wasm aggregated_chart_notebook.py -o aggregated-chart-notebook.html --mode edit
              marimo export html-wasm simple_element_notebook.py -o simple-element-notebook.html --mode edit

          # Jupyter notebooks
          - name: üìÑ Convert .py editable notebooks into .ipynb
            working-directory: docs/examples/notebooks
            run: python convert_notebooks_py_to_ipynb.py

          - name: Commit and push generated .ipynb notebooks
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
              commit_message: 'Update .ipynb notebooks for MyBinder [skip ci]'
              branch: main
              file_pattern: 'docs/examples/notebooks/*.ipynb'
              commit_user_name: github-actions[bot]
              commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
              git_push: true
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: ‚ùå Remove convert_notebooks_py_to_ipynb.py file from GitHub Pages
            working-directory: docs/examples/notebooks
            run: rm -f convert_notebooks_py_to_ipynb.py  # Remove from GitHub Pages

          - name: üì¶ Upload Pages Artifact
            uses: actions/upload-pages-artifact@v3
            with:
                path: docs/

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            pages: write
            id-token: write

        steps:
            - name: üåê Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: github-pages